name: aural-travels
channels:
    - pytorch
    - conda-forge
dependencies:
    - python=3.9
    - pytorch=1.8.1
    - torchvision=0.9.1
    - pandas=1.2.3
    - matplotlib
    - jupyterlab
    - requests
    - pillow
    - gitpython
    - mutagen
    - librosa

    - pip:
        - git+https://github.com/leod/scdata.git#egg=scdata
        - git+https://github.com/lucidrains/DALLE-pytorch.git#egg=dalle-pytorch